workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH == "develop"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH =~ /^feature\/.*/
    - when: never

stages:
  - lint
  - test
  - build
  - build-image
  - deploy

include:
  - local: "devops/ci/gitlab/lint.yml"
  - local: "devops/ci/gitlab/test.yml"
  - local: "devops/ci/gitlab/build.yml"
  - local: "devops/ci/gitlab/security.yml"
  - local: "devops/ci/gitlab/build-image.yml"
