networks:
  db:
    internal: true
  app:
    driver: bridge

volumes:
  postgres_data:

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      POSTGRES_DB: ${POSTGRES_DB:-main}
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./devops/docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - db
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-root} -d ${POSTGRES_DB:-main}",
        ]
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 10s

  backend:
    build:
      context: .
      dockerfile: ./devops/docker/backend/Dockerfile.backend.prod
      args:
        BACKEND_PORT: ${BACKEND_PORT:-3000}
    restart: always
    environment:
      BACKEND_PORT: ${BACKEND_PORT:-3000}
      DATABASE_URL: postgresql://${POSTGRES_USER:-root}:${POSTGRES_PASSWORD:-root}@db:5432/${POSTGRES_DB:-main}
      CORS_ORIGIN: ${CORS_ORIGIN:-}
      NODE_ENV: production
    networks:
      - db
      - app
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:${BACKEND_PORT:-3000}/health || exit 1",
        ]
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: .
      dockerfile: ./devops/docker/frontend/Dockerfile.frontend.prod
      args:
        FRONTEND_PORT: ${VITE_FRONTEND_PORT:-8088}
        VITE_FRONTEND_API_URL: ${VITE_FRONTEND_API_URL:-/api}
    restart: always
    environment:
      FRONTEND_PORT: ${VITE_FRONTEND_PORT:-8088}
    networks:
      - app
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://127.0.0.1:${VITE_FRONTEND_PORT:-8088}/ || exit 1",
        ]
      interval: 3s
      timeout: 5s
      retries: 3
      start_period: 20s

  nginx:
    image: nginx:1.27-alpine
    restart: always
    ports:
      - ${HTTP_PORT:-80}:80
    volumes:
      - ./devops/docker/nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app
    environment:
      - BACKEND_PORT=${BACKEND_PORT:-3000}
      - VITE_FRONTEND_PORT=${VITE_FRONTEND_PORT:-8088}
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://localhost || exit 1"]
      interval: 3s
      timeout: 5s
      retries: 3
      start_period: 5s
