# syntax=docker/dockerfile:1.7

FROM node:20-alpine

WORKDIR /app

ARG VITE_FRONTEND_PORT=${VITE_FRONTEND_PORT}

ENV NODE_ENV=development
ENV VITE_FRONTEND_PORT=$VITE_FRONTEND_PORT

RUN apk add --no-cache curl && corepack enable

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY frontend/package.json ./frontend/package.json

RUN --mount=type=cache,id=pnpm-store,target=/pnpm/store \
    pnpm install --frozen-lockfile --filter ./frontend...

COPY frontend ./frontend

EXPOSE ${VITE_FRONTEND_PORT}

CMD ["sh", "-c", "pnpm --filter ./frontend... exec vite --host 0.0.0.0 --port ${VITE_FRONTEND_PORT}"]
