build:
  stage: build
  image: node:20-bookworm

  allow_failure: false

  before_script:
    - corepack enable
    - pnpm install --frozen-lockfile

  script:
    - pnpm build

  cache:
    key: "turbo-${CI_COMMIT_REF_SLUG}"
    paths:
      - .turbo/cache
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "develop"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH =~ /^feature\/.*/
    - changes:
        - "**/*.ts"
        - "**/*.tsx"
        - "**/*.js"
        - "**/*.jsx"
    - when: never
