build:
  stage: build
  image: node:20-bookworm

  before_script:
    - corepack enable
    - pnpm install --frozen-lockfile

  script:
    - pnpm build

  cache:
    key: "turbo-${CI_COMMIT_REF_SLUG}"
    paths:
      - .turbo/cache
  rules:
    - changes:
        - "**/*.ts"
        - "**/*.tsx"
        - "**/*.js"
        - "**/*.jsx"
