.feature-branch-rules:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "develop"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH =~ /^feature\/.*/

.node-job:
  image: node:22-alpine
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest --activate
    - pnpm install --frozen-lockfile

.docker-node-job:
  image: node:22-alpine
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  services:
    - name: docker:24.0.5-dind
      alias: docker
  before_script:
    - apk add --no-cache docker-cli docker-compose
    - corepack enable
    - corepack prepare pnpm@latest --activate
    - pnpm install --frozen-lockfile

test:unit:
  stage: test
  extends:
    - .feature-branch-rules
    - .node-job
  cache:
    key: "turbo-${CI_COMMIT_REF_SLUG}"
    paths:
      - .turbo/cache
  allow_failure: false
  script:
    - cd backend
    - pnpm run test:unit
  artifacts:
    when: always
    reports:
      junit:
        - backend/junit/unit.xml

test:integration:
  stage: test
  extends:
    - .feature-branch-rules
    - .docker-node-job
  allow_failure: false
  variables:
    API_URL: "http://docker:${BACKEND_PORT}"
  cache:
    key: "turbo-${CI_COMMIT_REF_SLUG}"
    paths:
      - .turbo/cache
  script:
    #docker comand with multiple compose files to start only db and backend services
    - docker compose -f docker-compose.prod.yaml -f docker-compose.ci.yaml build db backend
    - docker compose -f docker-compose.prod.yaml -f docker-compose.ci.yaml up -d db backend
    - cd backend
    - pnpm run test:integration
    - cd ..
    - docker compose -f docker-compose.prod.yaml -f docker-compose.ci.yaml down
  artifacts:
    when: always
    reports:
      junit:
        - backend/junit/integration.xml

test:e2e:
  stage: test
  extends:
    - .feature-branch-rules
    - .docker-node-job
  allow_failure: true
  variables:
    FRONTEND_URL: "http://docker:${HTTP_PORT}"
    API_URL: "http://docker:${HTTP_PORT}${VITE_FRONTEND_API_URL}"
  cache:
    key: "turbo-${CI_COMMIT_REF_SLUG}"
    paths:
      - .turbo/cache
  script:
    - docker compose -f docker-compose.prod.yaml up -d db backend frontend nginx
    - cd backend
    - pnpm run test:e2e
    - cd ..
    - docker compose -f docker-compose.prod.yaml down
  artifacts:
    when: always
    reports:
      junit:
        - backend/junit/e2e.xml

test:security-scan:
  stage: test
  extends: .feature-branch-rules
  allow_failure: true
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .trivycache/
  services:
    - docker:24.0.5-dind
  script:
    - trivy image --download-db-only --cache-dir .trivycache
    - trivy fs --exit-code 1 --severity HIGH,CRITICAL --cache-dir .trivycache/ .
    - trivy config --exit-code 1 --severity HIGH,CRITICAL devops/docker/
